### ISSUE TITLE
Is there a way to put images/icons in the dropdown menu?

### ISSUE THREAD

**Issue by broAhmed** [cschleiden/vsts-extension-tags-mru#1]
Hi there! Your repo was instrumental in getting me up and running with a dropdown menu in my TFS 2017 extension. I'm wondering if there's a way to put an image/icon in the:

1. parent dropdown
2. child items

Example:
![images in work item dropdown menu](https://cloud.githubusercontent.com/assets/2554509/23178715/57fb2202-f820-11e6-94f0-a769ccbedbeb.JPG)

Thanks a ton!

**Comment by cschleiden** [comment]
@broahmed sure, have a look at this: https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/controls/menubar

Just return an `icon` property with a path to an image.

**Comment by broAhmed** [comment]
Awesome! Figures that I missed it in the docs. Thanks a ton!
